name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache: true

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Build
        run: go build -v .
